#ifndef TENSORFLOW_COMPILER_XLA_SERVICE_SPMD_PARTITION_ID_ELIMINATOR_H_
#define TENSORFLOW_COMPILER_XLA_SERVICE_SPMD_PARTITION_ID_ELIMINATOR_H_

#include "tensorflow/compiler/xla/service/hlo_pass_interface.h"

namespace xla {
namespace spmd {

// Remove the partition-id generated by SPMD partitioner.
// This partition-id does not work as input to neuron-cc.
// Instead, we create a parameter that takes in partition-id during runtime.
//
// TODO: before and after
// Before:
//
// After:
// 

class PartitionIdEliminator : public HloModulePass {
 public:
  PartitionIdEliminator() = default;
  ~PartitionIdEliminator() override = default;
  absl::string_view name() const override {
    return "partition_id_eliminator";
  }

  StatusOr<bool> Run(HloModule* module) override;
};

}  // namespace spmd
}  // namespace xla

#endif  // TENSORFLOW_COMPILER_XLA_SERVICE_SPMD_PARTITION_ID_ELIMINATOR_H_
